#!/usr/bin/env bash
# This script runs infinitely and prints a message when it receives SIGTERM

# Define a function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap the SIGTERM signal and call the handler
trap 'handle_sigterm' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
