#!/usr/bin/env bash
# This script kills the 7-highlander process using SIGKILL

# Find the PID(s) of 7-highlander
pids=$(pgrep -f "7-highlander")

# Send SIGKILL (signal 9) to each PID
for pid in $pids; do
    kill -9 "$pid"
done
