#!/usr/bin/env bash
# This script prints numbers from 1 to 20 with special messages for superstitious numbers using a case statement
count=1
while [ $count -le 20 ]; do
    case $count in
        4)
            echo "4"
            echo "bad luck from China"
            ;;
        9)
            echo "9"
            echo "bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$count"
            ;;
    esac
    count=$((count + 1))
done
